### PR TITLE
feat: deploy latest audited PW MSCA contract on EP0.6

### PR DESCRIPTION
**Pull request by ashutosh-ukey**
## Summary

Make some script updates and add deployment logs for the latest audited versions of PW MSCA contracts. Contracts were deployed and verified on all of the below chains:

- MATIC-AMOY
- ARB-SEPOLIA
- ETH-SEPOLIA
- MATIC
- ARB
- ETH

Addresses of the deployed contracts (same across all of the deployed chains): 
- PluginManager: 0x3169Ad878021B87C9CaA9b5CDA740ff3ca270Ce9
- SingleOwnerMSCAFactory: 0xa233b124D7b9CFF2D38cB62319e1A3f79144B490
- SingleOwnerMSCA: 0xeF3d10Df6e8eeAa925dA46ea12a6F17aB7F43B70

### Checklist
- [ ] Did you add new tests and confirm all tests pass? (`yarn test`)
- [ ] Did you update relevant docs? (docs are found in the `docs` folder)
- [ ] Do your commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [x] Does your PR title also follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard?
- [ ] If you have a breaking change, is it [correctly reflected in your commit message](https://www.conventionalcommits.org/en/v1.0.0/#examples)? (e.g. `feat!: breaking change`)
- [x] Did you run lint (`yarn lint`) and fix any issues?
- [x] Did you run formatter (`yarn format:check`) and fix any issues (`yarn format:write`)?

### CODE REVIEW

**Comment by huaweigu** [comment]
[Looks good](https://blockscan.com/address/0xa233b124D7b9CFF2D38cB62319e1A3f79144B490)! Good to go?

**Comment by ashutosh-ukey** [comment]
@huaweigu not yet, just need to add the stdout json for SingleOwnerMSCA!

**Comment by huaweigu** [comment]
nitpick, please use conventional commits for future PRs, although it doesn't matter because PR title will be used as the commit after squashing

**Comment by huaweigu** [comment]
> @huaweigu not yet, just need to add the stdout json for SingleOwnerMSCA (for verification).

Got it, thanks!

**Review by huaweigu — APPROVED** [review]

**Pull request merged**
